package github

// code snippet https://github.com/while-loop/todo/blob/cc6b554cccfd3598f6b6342d69c78abcbc5d0128/pkg/app.go#L17-L25
// footer  ###### This issue was generated by [todo](https://github.com/while-loop/todo).
